apiVersion: v1
kind: Pod
metadata:
  name: spatop-pod
spec:
  securityContext:
    runAsUser: 0
    fsGroup: 0
  containers:
  - name: spatop-container
    image:  gitlab-registry.nrp-nautilus.io/mquinnan/top-spanet:spatop-container
    command: ["/bin/bash", "-c", "sleep infinity"]
    stdin: true
    tty: true
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: 30Gi
        cpu: 4
      requests:
        nvidia.com/gpu: 1
        memory: 30Gi
        cpu: 3
    volumeMounts:
    - mountPath: /spatopvol
      name: spatopvol
  restartPolicy: Never
  volumes:
    - name: spatopvol
      persistentVolumeClaim:
        claimName: spatopvol